FROM julia:latest

WORKDIR /app

COPY Earthquakes_main.jl /app/
COPY src/updater /app/src/updater/
COPY src/database_connection.jl /app/src/
COPY src/updater/database/grouper /app/src/updater/database/grouper/

COPY Project.toml /app/
COPY Manifest.toml /app/
COPY setup.jl /app/


RUN julia setup.jl


CMD ["julia", "--project=@.", "Earthquakes_main.jl"]
